.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH k2i-maintenance-help 1  "k2i-maintenance-help "
.SH NAME
k2i\-maintenance\-help \- Print this message or the help of the given subcommand(s)
.SH SYNOPSIS
\fBk2i\-maintenance\-help\fR [\fB\-h\fR|\fB\-\-help\fR] [\fIsubcommands\fR]
.SH DESCRIPTION
Print this message or the help of the given subcommand(s)
.SH OPTIONS
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
.TP
[\fIsubcommands\fR]
Command path to print help for
