.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH k2i-maintenance-expire-snapshots 1  "k2i-maintenance-expire-snapshots "
.SH NAME
k2i\-maintenance\-expire\-snapshots \- Expire old snapshots
.SH SYNOPSIS
\fBk2i\-maintenance\-expire\-snapshots\fR [\fB\-h\fR|\fB\-\-help\fR]
.SH DESCRIPTION
Expire old snapshots
.SH OPTIONS
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help (see a summary with \*(Aq\-h\*(Aq)
.SH EXTRA
BEHAVIOR:
  Identifies snapshots older than snapshot_retention_days and removes old
  snapshot metadata. Data files still referenced by retained snapshots are not
  deleted.
