.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH k2i-completions-bash 1  "k2i-completions-bash "
.SH NAME
k2i\-completions\-bash \- Generate bash completions
.SH SYNOPSIS
\fBk2i\-completions\-bash\fR [\fB\-h\fR|\fB\-\-help\fR]
.SH DESCRIPTION
Generate bash completions
.SH OPTIONS
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help (see a summary with \*(Aq\-h\*(Aq)
.SH EXTRA
EXAMPLE:
  k2i completions bash > ~/.local/share/bash\-completion/completions/k2i
